server.port=8080

spring.application.name=api-gateway

# CORS configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins[0]=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins[1]=http://localhost:4173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# Discovery locator
spring.cloud.gateway.discovery.locator.enabled=false

# Routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=account-service
spring.cloud.gateway.routes[1].uri=lb://account-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/accounts/**

spring.cloud.gateway.routes[2].id=transaction-service
spring.cloud.gateway.routes[2].uri=lb://transaction-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/transactions/**

spring.cloud.gateway.routes[3].id=close-account-service
spring.cloud.gateway.routes[3].uri=lb://close-account-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/close-account/**

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Logging
logging.level.org.springframework.cloud.gateway=INFO
